CREATE TABLE IF NOT EXISTS STATISTICS
(
    ID              BIGSERIAL PRIMARY KEY,
    SHORT_URL       VARCHAR(200) NOT NULL,
    LONG_URL        VARCHAR(200) NOT NULL,
    COUNTER         INTEGER NOT NULL
    );